version: '3'

services:

  controller:
    build: ./controller

  mavros:
    image: uobflightlabstarling/starling-mavros:v0.1.0
    command: ros2 launch launch/mavros_bridge.launch.xml
    environment:
      - "MAVROS_TGT_FIRMWARE=apm"
      - "MAVROS_TGT_SYSTEM=1"
      - "MAVROS_FCU_URL=tcp-l://0.0.0.0:5760"
      - "MAVROS_GCS_URL=tcp-l://:5761"
      - "MAVROS_CONFIG_PATH=/mavros_config_ap.yaml"
      - "MAVROS_PLUGINLISTS_PATH=/mavros_pluginlists_ap.yaml"
    ports:
      - "5761:5761"

  rosbridge-suite:
    image: uobflightlabstarling/rosbridge-suite:v0.1.0
    ports:
      - "9090:9090"
